//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShtrihM.SCA.Packaging.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Msgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShtrihM.SCA.Packaging.Localization.Msgs", typeof(Msgs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание на отгрузку не может быть выполнено, так как продукция с кодом {0} все еще не отгружена..
        /// </summary>
        public static string loading_cannot_be_completed_because_product_with_code_0_is_not_loaded_yet {
            get {
                return ResourceManager.GetString("loading_cannot_be_completed_because_product_with_code_0_is_not_loaded_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено задание на отгрузку с № {0}..
        /// </summary>
        public static string loading_with_number_0_cannot_be_found {
            get {
                return ResourceManager.GetString("loading_with_number_0_cannot_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание на отгрузку № {0} выполнено или не готово к отгрузке..
        /// </summary>
        public static string loading_with_number_0_is_completed_or_not_prepared {
            get {
                return ResourceManager.GetString("loading_with_number_0_is_completed_or_not_prepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано новое место хранения продукции..
        /// </summary>
        public static string new_product_bin_is_not_specified {
            get {
                return ResourceManager.GetString("new_product_bin_is_not_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан номер задания на отгрузку..
        /// </summary>
        public static string order_number_is_not_defined {
            get {
                return ResourceManager.GetString("order_number_is_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано место хранения продукции..
        /// </summary>
        public static string product_bin_is_not_defined {
            get {
                return ResourceManager.GetString("product_bin_is_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В продукции c кодом {0} не определено место хранения..
        /// </summary>
        public static string product_bin_is_not_specified_in_product_wtih_code_0 {
            get {
                return ResourceManager.GetString("product_bin_is_not_specified_in_product_wtih_code_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный код продукции {0}..
        /// </summary>
        public static string product_code_0_is_invalid {
            get {
                return ResourceManager.GetString("product_code_0_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось определить код продукции..
        /// </summary>
        public static string product_code_is_not_defined {
            get {
                return ResourceManager.GetString("product_code_is_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти продукцию..
        /// </summary>
        public static string product_does_not_exist {
            get {
                return ResourceManager.GetString("product_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти продукцию с кодом {0}..
        /// </summary>
        public static string product_with_code_0_cannot_be_found {
            get {
                return ResourceManager.GetString("product_with_code_0_cannot_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукция с кодом {0} уже отгружена..
        /// </summary>
        public static string product_with_code_0_is_already_loaded {
            get {
                return ResourceManager.GetString("product_with_code_0_is_already_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукция c кодом {0} не предназначена для отгрузки..
        /// </summary>
        public static string product_with_code_0_is_not_prepared_for_loading {
            get {
                return ResourceManager.GetString("product_with_code_0_is_not_prepared_for_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось опредлить пользователя..
        /// </summary>
        public static string user_is_not_defined {
            get {
                return ResourceManager.GetString("user_is_not_defined", resourceCulture);
            }
        }
    }
}
